/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "validation": {
        "validation_error": string;
        "property_required": string;
        "property_not_email": string;
        "property_min_length": string;
        "property_max_length": string;
        "property_is_string": string;
        "property_is_number": string;
        "property_is_boolean": string;
    };
    "auth": {
        "user_already_exists": string;
        "invalid_credentials": string;
        "logged_in": string;
        "logged_out": string;
        "unauthorized": string;
    };
    "orders": {
        "items_not_found": string;
        "order_not_found": string;
        "invalid_idempotency_key": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
